"""
API Routes — FastAPI endpoint definitions.

Layer contract:
  - API layer ONLY handles request/response serialisation
  - API layer MUST NOT access DB, tools, or graph nodes directly
  - The graph is STATELESS — all DB interaction is pre/post-graph here

POST /query flow:
  1. Extract user_id from JWT
  2. ConversationService: get or create conversation
  3. ConversationService: load recent message history
  4. Inject conversation_id + message_history + user_id into GraphState
  5. Invoke compiled_graph
  6. Post-graph: save conversational turn to messages table
  7. Determine response_type from top intent
  8. Return structured QueryResponse

Graph nodes and tools MUST trust GraphState.user_id only.
No node reads auth headers directly.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional

from fastapi import APIRouter, Depends, HTTPException

from app.api.dependencies import get_current_user
from app.models.schemas import QueryRequest, QueryResponse
from app.models.state import GraphState

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# Lazy service accessors — avoid circular imports at module load time
# ---------------------------------------------------------------------------

def _get_conversation_service():
    """Build ConversationService with its repositories."""
    from app.services.db.connection import db_manager
    from app.services.db.conversation_repository import ConversationRepository
    from app.services.db.message_repository import MessageRepository
    from app.services.conversation_service import ConversationService

    return ConversationService(
        conversation_repo=ConversationRepository(db_manager),
        message_repo=MessageRepository(db_manager),
    )


# Module-level singleton (built once on first call)
_conversation_service = None


def _conversation_service_instance():
    global _conversation_service
    if _conversation_service is None:
        _conversation_service = _get_conversation_service()
    return _conversation_service


# ---------------------------------------------------------------------------
# Response type resolution
# ---------------------------------------------------------------------------

def _resolve_response_type(
    final_state: GraphState,
    tool_results: Dict[str, Any],
) -> tuple[str, Optional[Dict[str, Any]]]:
    """
    Determine the response_type and structured data payload for the frontend.

    Returns:
        (response_type: str, data: Optional[dict])
    """
    intents = final_state.get("intents", [])
    top_intent = intents[0]["type"] if intents else "UNKNOWN"
    is_safe = final_state.get("is_safe")

    # Safety refusal
    if is_safe is False:
        return "ERROR", None

    # Small talk — plain text
    if top_intent == "SMALL_TALK":
        return "TEXT", None

    # Unknown intent
    if top_intent == "UNKNOWN":
        return "TEXT", None

    # Train search with results
    if top_intent == "SEARCH_TRAINS":
        search_result = tool_results.get("search_trains", {})
        data = search_result.get("data") if isinstance(search_result, dict) else None
        if data and data.get("total", 0) > 0:
            return "TRAIN_LIST", data
        return "TEXT", None

    return "TEXT", None


# ---------------------------------------------------------------------------
# POST /query — main LangGraph assistant endpoint (JWT-protected)
# ---------------------------------------------------------------------------

@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Submit a natural language query to the railway assistant",
    description=(
        "Accepts a user query and returns a structured response generated by the "
        "LangGraph workflow. Requires a valid JWT in the Authorization header. "
        "Manages conversation history automatically."
    ),
)
def query(
    request: QueryRequest,
    user_id: str = Depends(get_current_user),
) -> QueryResponse:
    """
    Invoke the LangGraph workflow with full conversation context.

    Pre-graph:
      - Resolve/create conversation for user
      - Load recent message history from DB
      - Inject into GraphState

    Graph execution:
      - Guardrail → Intent → Planner → Router/Tools → Responder → Logger

    Post-graph:
      - Persist the conversational turn (user + assistant messages)
      - Determine response_type for frontend rendering
      - Return structured QueryResponse
    """
    from app.graph.workflow import compiled_graph

    logger.info(
        "POST /query | user_id=%s | query=%r",
        user_id,
        request.query[:80],
    )

    # ------------------------------------------------------------------
    # Pre-graph: conversation context
    # ------------------------------------------------------------------
    conv_service = _conversation_service_instance()

    conversation_id = conv_service.get_or_create_conversation(user_id)
    message_history = conv_service.load_recent_messages(conversation_id)

    logger.debug(
        "Conversation %s | %d prior messages loaded",
        conversation_id, len(message_history),
    )

    # ------------------------------------------------------------------
    # Build initial GraphState — Application Layer fields only
    # ------------------------------------------------------------------
    initial_state: GraphState = {
        "user_query":       request.query,
        "user_id":          user_id,          # from JWT — never from request body
        "conversation_id":  conversation_id,
        "message_history":  message_history,
    }

    # ------------------------------------------------------------------
    # Graph invocation
    # ------------------------------------------------------------------
    try:
        final_state: GraphState = compiled_graph.invoke(initial_state)
    except Exception as exc:
        logger.error("Graph execution failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=500,
            detail="An internal error occurred. Please try again.",
        )

    final_response: str = final_state.get("final_response") or (
        "I was unable to generate a response. Please try again."
    )

    # ------------------------------------------------------------------
    # Post-graph: persist conversational turn
    # ------------------------------------------------------------------
    try:
        conv_service.save_turn(
            conversation_id=conversation_id,
            user_content=request.query,
            assistant_content=final_response,
        )
    except Exception as exc:
        # Suppress — conversation persistence must never break the response
        logger.error("Post-graph conversation save failed (suppressed): %s", exc)

    # ------------------------------------------------------------------
    # Determine response_type + structured data for frontend
    # ------------------------------------------------------------------
    tool_results: Dict[str, Any] = final_state.get("tool_results", {})
    response_type, data = _resolve_response_type(final_state, tool_results)

    return QueryResponse(
        message=final_response,
        response_type=response_type,
        data=data,
    )
