"""
Pydantic request/response schemas for the API layer.

These schemas are intentionally decoupled from GraphState so that
the API contract can evolve independently from the graph internals.
"""

from typing import Any, Dict, Literal, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# POST /query
# ---------------------------------------------------------------------------

class QueryRequest(BaseModel):
    """Incoming user query payload.

    Note: ``user_id`` is no longer part of the request body —
    it is extracted from the JWT by the ``get_current_user`` dependency.
    """
    query: str = Field(..., min_length=1, description="Natural language query from the user")


class QueryResponse(BaseModel):
    """
    Structured response returned to the client after graph execution.

    Fields:
        message:       Human-readable reply generated by the assistant.
        response_type: Rendering hint for the frontend. Values:
                         TEXT        — plain conversational message
                         TRAIN_LIST  — train search results (render as cards)
                         PNR_STATUS  — PNR status result
                         RAG_RESPONSE — FAQ/RAG grounded response
                         ERROR       — error/fallback message
        data:          Optional structured payload for frontend rendering.
                       For TRAIN_LIST: { trains: [...], total: int, query_echoed: {...} }
                       For PNR_STATUS: { pnr_number, status, train, ... } (future)
                       For TEXT / ERROR: null
    """
    message: str = Field(..., description="Natural-language reply generated by the system")
    response_type: str = Field(
        default="TEXT",
        description="Frontend rendering hint: TEXT | TRAIN_LIST | PNR_STATUS | RAG_RESPONSE | ERROR",
    )
    data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional structured payload for rich frontend rendering",
    )


# ---------------------------------------------------------------------------
# Authentication schemas
# ---------------------------------------------------------------------------

class RegisterRequest(BaseModel):
    """Payload for POST /auth/register."""
    email: str = Field(..., description="User email address")
    password: str = Field(..., min_length=6, description="User password (min 6 characters)")


class LoginRequest(BaseModel):
    """Payload for POST /auth/login."""
    email: str = Field(..., description="User email address")
    password: str = Field(..., description="User password")


class RegisterResponse(BaseModel):
    """Response for successful registration."""
    id: str = Field(..., description="Newly created user UUID")
    email: str = Field(..., description="Registered email")
    message: str = Field(default="Registration successful")


class TokenResponse(BaseModel):
    """Response for successful login — contains a JWT."""
    access_token: str = Field(..., description="JWT access token")
    token_type: str = Field(default="bearer")


# ---------------------------------------------------------------------------
# Future schemas (stub — add detail when endpoint is implemented)
# ---------------------------------------------------------------------------

class TrainListResponse(BaseModel):
    """Response for GET /trains (future endpoint)."""
    trains: list = Field(default_factory=list)
    total: int = 0


class PNRStatusResponse(BaseModel):
    """Response for GET /pnr/{pnr_id} (future endpoint)."""
    pnr: str = ""
    status: str = ""
    detail: dict = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Conversation & Message History Schemas (Frontend Sidebar)
# ---------------------------------------------------------------------------

class ConversationItem(BaseModel):
    """A single conversation in the sidebar list."""
    id: str = Field(..., description="Conversation UUID")
    created_at: str = Field(..., description="ISO timestamp of conversation creation")


class ConversationListResponse(BaseModel):
    """Response for GET /conversations."""
    conversations: list[ConversationItem] = Field(
        default_factory=list,
        description="List of user's conversations, newest first",
    )


class MessageItem(BaseModel):
    """A single message in conversation history."""
    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="Message text")
    created_at: str = Field(..., description="ISO timestamp of message creation")


class ConversationMessagesResponse(BaseModel):
    """Response for GET /conversations/{conversation_id}/messages."""
    conversation_id: str = Field(..., description="Conversation UUID")
    messages: list[MessageItem] = Field(
        default_factory=list,
        description="All messages in this conversation, oldest first",
    )
